99cats/ninety9cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats
end

99cats/ninety9cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

99cats/ninety9cats/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    colors = ["Red", "Blue", "Green", "Aquamarine", "Orange", "Brown", "Pink"]

    validates :birth_date, presence: true
    validates :name, presence: true
    validates :color, presence: true, inclusion: { in: colors, message: "This is not a color of a cat!"}
    validates :sex, presence: true
    validates :description, presence: true

    def age
        time_ago_in_words(birth_date)
    end

    
end

99cats/ninety9cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

99cats/ninety9cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index 
        @cats = Cat.all
        render :index 
    end

    def show 
        @cat = Cat.find(params[:id])
        render :show
    end

    def create
        @cat = Cat.new(cat_params)
        
        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new
        end

    end

    def new
        render :new
    end

    


end

99cats/ninety9cats/app/helpers/application_helper.rb
module ApplicationHelper
end

99cats/ninety9cats/app/views/cats/_cat.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%= cat.name %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Attribute</td>
            <td>Values</td>
        </tr>
        <tr>
            <td>Birth Date</td>
            <td><%= cat.birth_date %></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= cat.color %></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= cat.sex %> </td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= cat.description %></td>
        </tr>
    </tbody>
</table>

99cats/ninety9cats/app/views/cats/index.html.erb
<h1> Here are all of my cats: </h1>
<ul>
<% @cats.each do |cat| %>
    <li> <%= cat.name %> </li>
    <li> <%= cat.birth_date %> </li>
    <li> <%= cat.sex %> </li>
    <li> <%= cat.color %> </li>
    <li> <%= cat.age %> </li>
    <li> <%= cat.description %> </li>
    <li> 
        <a href="<%= cat_url(cat) %>">Cat's show page</a>
    </li>
    <br />
<% end %>

</ul>

99cats/ninety9cats/app/views/cats/new.html.erb
<form action="<%= cats_url %>" method="post">
    <label> Name:
        <input type="text" name="cat[name]">
    </label>

    <label> Birth Date:
        <input type="date" name="cat[birth_date]">
    </label>

    <label> Color:
        <input type="text" name="cat[color]">
    </label>

    <input type="submit" value="Create Cat">

</form>

99cats/ninety9cats/app/views/cats/show.html.erb
<%= render 'cat',  cat: @cat, action: :show %>

99cats/ninety9cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ninety9cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>